const VALID_BLACK_KEYS = ['s', 'd', 'g', 'h', 'j', 'l', ';', '2', '3', '4', '6', '7', '9', '0', '-'];
const VALID_WHITE_KEYS = ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '['];
const VALID_KEYS = [...VALID_BLACK_KEYS, ...VALID_WHITE_KEYS];
const NOTES = [
  'c3', 'dfl3', 'd3', 'efl3',
  'e3', 'f3', 'gfl3', 'g3',
  'afl3', 'a3', 'bfl3', 'b3',
  'c4', 'dfl4', 'd4', 'efl4',
  'e4', 'f4', 'gfl4', 'g4',
  'afl4', 'a4', 'bfl4', 'b4',
  'c5', 'dfl5', 'd5', 'efl5',
  'e5', 'f5', 'gfl5', 'g5',
  'afl5', 'a5', 'bfl5', 'b5'
];
const NOTE_TO_KEY = {
  c3: 'z',
  dfl3: 's',
  d3: 'x',
  efl3: 'd',
  e3: 'c',
  f3: 'v',
  gfl3: 'g',
  g3: 'b',
  afl3: 'h',
  a3: 'n',
  bfl3: 'j',
  b3: 'm',
  c4: ',',
  dfl4: 'l',
  d4: '.',
  efl4: ';',
  e4: '/',
  f4: 'q',
  gfl4: '4',
  g4: 'w',
  afl4: '5',
  a4: 'e',
  bfl4: '4',
  b4: 'r',
  c5: 't',
  dfl5: '6',
  d5: 'y',
  efl5: '7',
  e5: 'u',
  f5: 'i',
  gfl5: '9',
  g5: 'o',
  afl5: '0',
  a5: 'p',
  bfl5: '-',
  b5: '[',
};
const KEY_TO_NOTE = {
  z: 'c3',
  s: 'dfl3',
  x: 'd3',
  d: 'efl3',
  c: 'e3',
  v: 'f3',
  g: 'gfl3',
  b: 'g3',
  h: 'afl3',
  n: 'a3',
  j: 'bfl3',
  m: 'b3',
  ',': 'c4',
  l: 'dfl4',
  '.': 'd4',
  ';': 'efl4',
  '/': 'e4',
  q: 'f4',
  2: 'gfl4',
  w: 'g4',
  3: 'afl4',
  e: 'a4',
  4: 'bfl4',
  r: 'b4',
  t: 'c5',
  6: 'dfl5',
  y: 'd5',
  7: 'efl5',
  u: 'e5',
  i: 'f5',
  9: 'gfl5',
  o: 'g5',
  0: 'afl5',
  p: 'a5',
  '-': 'bfl5',
  '[': 'b5'
};
export {
  NOTES,
  VALID_KEYS,
  NOTE_TO_KEY,
  KEY_TO_NOTE,
};
