const VALID_BLACK_KEYS = ['s', 'd', 'g', 'h', 'j', 'l', ';', '2', '3', '4', '6', '7', '9', '0', '-'];
const VALID_WHITE_KEYS = ['z', 'x', 'c', 'v', 'b', 'n', 'm', ',', '.', '/', 'q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p', '['];
const VALID_KEYS = [...VALID_BLACK_KEYS, ...VALID_WHITE_KEYS];
const NOTES = [
  'c1', 'dfl1', 'd1', 'efl1',
  'e1', 'f1', 'gfl1', 'g1',
  'afl1', 'a1', 'bfl1', 'b1',
  'c2', 'dfl2', 'd2', 'efl2',
  'e2', 'f2', 'gfl2', 'g2',
  'afl2', 'a2', 'bfl2', 'b2',
  'c3', 'dfl3', 'd3', 'efl3',
  'e3', 'f3', 'gfl3', 'g3',
  'afl3', 'a3', 'bfl3', 'b3'
];
const NOTE_TO_KEY = {
  c1: 'z',
  dfl1: 's',
  d1: 'x',
  efl1: 'd',
  e1: 'c',
  f1: 'v',
  gfl1: 'g',
  g1: 'b',
  afl1: 'h',
  a1: 'n',
  bfl1: 'j',
  b1: 'm',
  c2: ',',
  dfl2: 'l',
  d2: '.',
  efl2: ';',
  e2: '/',
  f2: 'q',
  gfl2: '2',
  g2: 'w',
  afl2: '3',
  a2: 'e',
  bfl2: '4',
  b2: 'r',
  c3: 't',
  dfl3: '6',
  d3: 'y',
  efl3: '7',
  e3: 'u',
  f3: 'i',
  gfl3: '9',
  g3: 'o',
  afl3: '0',
  a3: 'p',
  bfl3: '-',
  b3: '[',
};
const KEY_TO_NOTE = {
  z: 'c1',
  s: 'dfl1',
  x: 'd1',
  d: 'efl1',
  c: 'e1',
  v: 'f1',
  g: 'gfl1',
  b: 'g1',
  h: 'afl1',
  n: 'a1',
  j: 'bfl1',
  m: 'b1',
  ',': 'c2',
  l: 'dfl2',
  '.': 'd2',
  ';': 'efl2',
  '/': 'e2',
  q: 'f2',
  2: 'gfl2',
  w: 'g2',
  3: 'afl2',
  e: 'a2',
  4: 'bfl2',
  r: 'b2',
  t: 'c3',
  6: 'dfl3',
  y: 'd3',
  7: 'efl3',
  u: 'e3',
  i: 'f3',
  9: 'gfl3',
  o: 'g3',
  0: 'afl3',
  p: 'a3',
  '-': 'bfl3',
  '[': 'b3'
};
export {
  NOTES,
  VALID_KEYS,
  NOTE_TO_KEY,
  KEY_TO_NOTE,
};
